import './globals.css'
import type { Metadata } from 'next'
import {useLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {NextIntlClientProvider} from 'next-intl';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'bl'}];
}

export default async function LocaleLayout({children, params: {locale}} 
  : {children: React.ReactNode, params:{locale:string}}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
 
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
